### PR TITLE
Generate changelog and add PR template

### PR DESCRIPTION
**Pull request by JordanMartinez**
Part of purescript/purescript#3984

### CODE REVIEW

**Review by thomashoneyman — APPROVED** [review]

**Comment by thomashoneyman** [comment]
The CI failure is unrelated to this PR (but ought to be fixed pre-release)

**Comment by JordanMartinez** [comment]
Let's just fix it in this PR.

**Comment by JordanMartinez** [comment]
Hm... CI fails because fun deps aren't propagated:
```
[1/1 NoInstanceFound] test/Main.purs:12:1

      v
  12  instance newtypeRecordNewtype ::
  13    TypeEquals inner { message :: String }
  14      => Newtype RecordNewtype inner
                                       ^
  
  No type class instance was found for
  
    Prim.Coerce.Coercible inner0
                          { message :: String
                          }
  
  while solving type class constraint
  
    Prim.Coerce.Coercible RecordNewtype
                          inner0
  
  while checking that expression #dict Coercible
    has type Coercible$Dict @Type RecordNewtype inner0
  in value declaration newtypeRecordNewtype
  
  where inner0 is a rigid type variable
          bound at (line 0, column 0 - line 0, column 0)

           Src   Lib   All
Warnings   0     0     0  
Errors     1     0     1  
```

**Comment by JordanMartinez** [comment]
I'm going to remove the previous commit so that this only focuses on the changelog and PR template.

**Comment by JordanMartinez** [comment]
Commit has been removed.

**Comment by JordanMartinez** [comment]
I'm addressing the Newtype instance issue in #14

**Pull request merged**
